services:
  wp:
    image: authldap_test:${WORDPRESS_VERSION:-6.4}-${PHP_VERSION:-8.3}
    build:
      context: dockersetup
      dockerfile: Dockerfile_wordpress
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
        WORDPRESS_VERSION: ${WORDPRESS_VERSION:-6.4}
    ports:
      - 80:80 # change ip if required
    volumes:
      - .:/var/www/html/wp-content/plugins/authldap
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "wppasswd"
      WORDPRESS_DEBUG: 0
    depends_on:
      db:
        condition: service_healthy
      openldap:
        condition: service_healthy
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/authldap
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "wppasswd"
    user: "33:33"
    depends_on:
      - db
      - wp

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 3306:3306 # change ip if required
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "wppasswd"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 10
      interval: 2s

  openldap:
    image: osixia/openldap:latest
#    build:
#      context: dockersetup
#      dockerfile: Dockerfile_ldap
    ports:
      - 3389:389
    volumes:
      - ./.ci/50-init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    command: "--copy-service --loglevel debug"
    restart: always
    environment:
      LDAP_LOG_LEVEL: "0"
      LDAP_TLS: "false"
      LDAP_ADMIN_PASSWORD: "insecure"
    healthcheck:
      test: ["CMD", "/usr/bin/ldapsearch", "-H",  "ldap://localhost/", "-x", "-s", "base", "-LLL", "+"]
      timeout: 1s
      retries: 10
      interval: 2s

volumes:
  db_data:
  wordpress:
