name: Behat Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT_LDAP: 3389
      PORT_LDAPS: 6363
      LDAP_ADMIN_PASSWORD: ${{ secrets.LDAP_ADMIN_PASSWORD }}
      LDAP_LOG_LEVEL: 0
    strategy:
      matrix:
        # operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
        wordpress-versions: ['6.1', '6.2', '6.3', '6.4']

    name: Test on PHP${{ matrix.php-versions }} with WordPress ${{ matrix.wordpress_version }}
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker compose -e PHP_VERSION=${{ matrix.php-version }} -e WORDPRESS_VERSION=${{ matrix.wordpress-versions }} -f docker-compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker compose logs openldap
      - name: run behat
        run: docker compose exec wp bash -c "cd wp-content/plugins/authldap && ./tools/behat"
